// Worker-side database access: per-camera config reads (cached, invalidated
// by NOTIFY config_changed) and event inserts. The worker writes events
// directly — same denormalized-label shape the connector ingest used, plus
// the provenance columns (preview_id, segment_key, dedup_key) from 0011.

import pg from "pg";
import type {
  Action,
  PolygonPoint,
  ScheduleWindow,
  Trigger,
} from "@surveillance/shared";
import type { EngineCameraConfig } from "./engine.js";
import type { FiredEvent } from "./engine.js";

export interface WorkerCameraConfig {
  cameraId: string;
  cameraLabel: string;
  connectorId: string;
  siteId: string;
  organizationId: string;
  engine: EngineCameraConfig;
  /** Serialized config for cheap change detection — the segment processor
   *  rebuilds a camera's engine (dropping tracker state) only when this
   *  actually changed. */
  fingerprint: string;
}

export interface EventInsert {
  /** Generated by the segment processor so the thumbnail can be uploaded
   *  under a key derived from it before the row lands. */
  id: string;
  fired: FiredEvent;
  config: WorkerCameraConfig;
  previewId: string;
  segmentKey: string;
  /** Upload key of the trigger-frame JPEG (snapshots/ keyspace), or null if
   *  the upload failed — events are worth more than thumbnails. */
  snapshotKey: string | null;
}

const CACHE_TTL_MS = 60_000;

export class WorkerDb {
  readonly pool: pg.Pool;
  private readonly cache = new Map<
    string,
    { config: WorkerCameraConfig | null; fetchedAt: number }
  >();

  constructor(databaseUrl: string) {
    this.pool = new pg.Pool({ connectionString: databaseUrl, max: 5 });
  }

  invalidateConfigCache(): void {
    this.cache.clear();
  }

  async getCameraConfig(cameraId: string): Promise<WorkerCameraConfig | null> {
    const cached = this.cache.get(cameraId);
    if (cached && Date.now() - cached.fetchedAt < CACHE_TTL_MS) return cached.config;
    const config = await this.fetchCameraConfig(cameraId);
    this.cache.set(cameraId, { config, fetchedAt: Date.now() });
    return config;
  }

  private async fetchCameraConfig(cameraId: string): Promise<WorkerCameraConfig | null> {
    const camRes = await this.pool.query<{
      id: string;
      label: string;
      connector_id: string;
      site_id: string;
      organization_id: string;
      timezone: string;
    }>(
      `SELECT cam.id, cam.label, cam.connector_id, c.site_id, c.organization_id, s.timezone
         FROM cameras cam
         JOIN connectors c ON c.id = cam.connector_id
         JOIN sites s ON s.id = c.site_id
        WHERE cam.id = $1`,
      [cameraId],
    );
    const cam = camRes.rows[0];
    if (!cam) return null;

    const [zoneRes, schedRes, ruleRes] = await Promise.all([
      this.pool.query<{ id: string; label: string; polygon: PolygonPoint[] }>(
        `SELECT id, label, polygon FROM zones WHERE camera_id = $1`,
        [cameraId],
      ),
      this.pool.query<{ id: string; windows: ScheduleWindow[] }>(
        `SELECT id, windows FROM schedules WHERE site_id = $1`,
        [cam.site_id],
      ),
      this.pool.query<{
        id: string;
        label: string;
        zone_id: string;
        schedule_id: string | null;
        trigger: Trigger;
        action: Action;
      }>(
        `SELECT r.id, r.label, r.zone_id, r.schedule_id, r.trigger, r.action
           FROM rules r
           JOIN zones z ON z.id = r.zone_id
          WHERE z.camera_id = $1 AND r.enabled`,
        [cameraId],
      ),
    ]);

    const engine: EngineCameraConfig = {
      timezone: cam.timezone,
      zones: zoneRes.rows.map((z) => ({ id: z.id, label: z.label, polygon: z.polygon })),
      schedules: schedRes.rows.map((s) => ({ id: s.id, windows: s.windows })),
      rules: ruleRes.rows.map((r) => ({
        id: r.id,
        label: r.label,
        zoneId: r.zone_id,
        scheduleId: r.schedule_id,
        trigger: r.trigger,
        severity: r.action.severity,
      })),
    };
    return {
      cameraId: cam.id,
      cameraLabel: cam.label,
      connectorId: cam.connector_id,
      siteId: cam.site_id,
      organizationId: cam.organization_id,
      engine,
      fingerprint: JSON.stringify(engine),
    };
  }

  /** Returns the number of rows actually inserted (dedup conflicts skipped). */
  async insertEvents(events: EventInsert[]): Promise<number> {
    let inserted = 0;
    for (const { id, fired, config, previewId, segmentKey, snapshotKey } of events) {
      const { rowCount } = await this.pool.query(
        `INSERT INTO events
           (id, organization_id, site_id, connector_id, rule_id, camera_id, zone_id,
            rule_label, camera_label, zone_label, trigger_type, severity,
            occurred_at, snapshot_key, metadata, preview_id, segment_key, dedup_key)
         VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
         ON CONFLICT (dedup_key) WHERE dedup_key IS NOT NULL DO NOTHING`,
        [
          id,
          config.organizationId,
          config.siteId,
          config.connectorId,
          fired.ruleId,
          config.cameraId,
          fired.zoneId,
          fired.ruleLabel,
          config.cameraLabel,
          fired.zoneLabel,
          fired.triggerType,
          fired.severity,
          new Date(fired.occurredAtMs).toISOString(),
          snapshotKey,
          JSON.stringify(fired.metadata),
          previewId,
          segmentKey,
          fired.dedupKey,
        ],
      );
      inserted += rowCount ?? 0;
    }
    return inserted;
  }

  async close(): Promise<void> {
    await this.pool.end();
  }
}
